version: '3.8'

services:
  launchsite:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_DATABASE_URL=postgres://quickjob:Pinokio590@@asgqcks08k8cosssk0kcwvk4:5432/postgres
      - VITE_DB_HOST=asgqcks08k8cosssk0kcwvk4
      - VITE_DB_PORT=5432
      - VITE_DB_NAME=postgres
      - VITE_DB_USER=quickjob
      - VITE_DB_PASSWORD=Pinokio590@@
      - VITE_APP_URL=https://your-domain.com
      - VITE_WHATSAPP_NUMBER=972000000000
      - VITE_CONTACT_EMAIL=launchsitex@gmail.com
    restart: unless-stopped
    networks:
      - launchsite-network

networks:
  launchsite-network:
    driver: bridge